name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Generate PDF document
        uses: hspaans/latexmk-action@v1.1.0
        with:
          format: pdf
          filename: main.tex
